In [1]:
import numpy as np

In [18]:
# Python list
py_list = [1, 2, 3, 4]

# NumPy array
np_array = np.array([1, 2, 3, 4])

print(type(py_list))
print(type(np_array))

print(py_list)
print(np_array)

print(py_list*2)
print(np_array*2)

for data in py_list:
    value = data*2
    print(value)

#creating array properly
a = np.array([10,20,30,40])
b = np.zeros(7)
c = np.ones(6)
d = np.linspace(0,20,5)
e = np.arange(0,10,3)

print(a)
print(b)
print(c)
print(d)
print(e)

#array properties

arr = np.array([3,6,9,12])

print("shape:",arr.shape) #dimension
print("size:",arr.size) #total elements
print("data type:",arr.dtype) #number type

#indexing and slicing

x = np.array([10,40,50,30])

print(x[0])
print(x[-1])
print(x[1:4])

x[2] = 80
print(x)





<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4]
[1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]
2
4
6
8
[10 20 30 40]
[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[ 0.  5. 10. 15. 20.]
[0 3 6 9]
shape: (4,)
size: 4
data type: int64
10
30
[40 50 30]
[10 40 80 30]
