In [2]:
import numpy as np

In [8]:
matrix = np.array([[1, 2],
                   [3, 4]])

print(matrix)
print("Shape:", matrix.shape)
print(matrix[0, 1])

#vectorized math
x = np.array([1,2,3,4,5,6])

print(x + 7)
print(x * 5)
print(x**2)
print(np.sqrt(x))
print(np.mean(x))
print(np.std(x))

#broadcasting

x = np.array([1, 2, 3])
y = 10

print(x + y)

#2d broadcasting
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A + 10)

#astronomy example

redshift = np.array([0.01,0.02,0.03,0.04])
c = 3e5 #km/s

velocity = c * redshift
print("velocity:",velocity)






[[1 2]
 [3 4]]
Shape: (2, 2)
2
[ 8  9 10 11 12 13]
[ 5 10 15 20 25 30]
[ 1  4  9 16 25 36]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
3.5
1.707825127659933
[11 12 13]
[[11 12 13]
 [14 15 16]]
velocity: [ 3000.  6000.  9000. 12000.]
